-- @description Project Startup Manager
-- @author DocShadrach (Code by Your Reaper Lua Expert)
-- @version 1.1
-- @about Manager interface with full status feedback (Bypassed, Saved, Linked, etc.).
-- @requirement ReaImGui

local r = reaper
local ctx = r.ImGui_CreateContext('StartupManager')

-- =========================================================
-- CONFIGURATION
-- =========================================================
local FILE_NAME = "project_startup_actions.lua"
local EXT_SECTION = "StartupManager"
local EXT_KEY = "ActionList"
local LOADER_SEARCH_NAME = "DocShadrach_Project Startup Loader" 
local WINDOW_W, WINDOW_H = 500, 450 
local WINDOW_OPACITY = 0.95
local MSG_DURATION = 3.0 -- Mensajes duran 3 segundos

-- =========================================================
-- DATA
-- =========================================================
local actions_list = {} 
local status_msg = ""
local status_clear_time = 0

-- =========================================================
-- HELPERS
-- =========================================================

function SetStatus(msg, is_error)
    status_msg = msg
    status_clear_time = r.time_precise() + MSG_DURATION
    return is_error == nil or not is_error 
end

function GetLocalFilePath()
    local _, proj_fn = r.EnumProjects(-1, "")
    if not proj_fn or proj_fn == "" then return nil end
    local path = proj_fn:match("(.*[/\\])")
    if path then return path .. FILE_NAME end
    return nil
end

function SaveData()
    local serialized = ""
    for _, item in ipairs(actions_list) do
        local state = item.enabled and "1" or "0"
        serialized = serialized .. item.id .. "|" .. item.name .. "|" .. state .. ";"
    end
    r.SetProjExtState(0, EXT_SECTION, EXT_KEY, serialized)
    r.MarkProjectDirty(0) 
    
    local path = GetLocalFilePath()
    if path then
        local f = io.open(path, "w")
        if f then
            f:write("-- Auto-generated by Project Startup Manager\n")
            f:write("local r = reaper\n\n")
            for _, item in ipairs(actions_list) do
                local prefix = item.enabled and "" or "-- "
                f:write(string.format('%sr.Main_OnCommand(r.NamedCommandLookup("%s"), 0) -- %s\n', prefix, item.id, item.name))
            end
            f:close()
            return true
        else
            return SetStatus("Error: Write failed.", true)
        end
    else
        return SetStatus("Saved to Project Data (Memory) only.", false)
    end
end

function LoadActions()
    actions_list = {}
    local loaded_from_file = false
    local loaded_from_ext = false
    
    local path = GetLocalFilePath()
    if path then
        local f = io.open(path, "r")
        if f then
            for line in f:lines() do
                local is_commented = line:match("^%s*%-%-")
                local id = line:match('NamedCommandLookup%("([^"]+)"%)')
                local name = line:match('%)%s%-%-%s(.*)$')
                
                if name and name:find("r.Main_OnCommand") then
                    local real_name = name:match('%-%-%s(.*)$')
                    if real_name then name = real_name end
                end

                if id then
                    table.insert(actions_list, {
                        id = id, 
                        name = name or "Unknown",
                        enabled = not is_commented
                    })
                end
            end
            f:close()
            loaded_from_file = true
        end
    end
    
    if not loaded_from_file then
        local retval, data = r.GetProjExtState(0, EXT_SECTION, EXT_KEY)
        if retval == 1 and data ~= "" then
            for item in data:gmatch("([^;]+)") do
                local id, name, state = item:match("^([^|]+)|([^|]+)|([^|]+)")
                if not state then id, name = item:match("^([^|]+)|(.*)") state = "1" end
                
                if id then
                    table.insert(actions_list, {
                        id = id, 
                        name = name or "Unknown", 
                        enabled = (state == "1")
                    })
                end
            end
            loaded_from_ext = true
        end
    end
    
    if loaded_from_ext and path and not loaded_from_file then
        if SaveData() then
            SetStatus("Synced: File regenerated.")
        end
    end
end

function GetCommandName(id)
    local text = r.CF_GetCommandText(0, r.NamedCommandLookup(id))
    if not text or text == "" then return id else return text end
end

function TrimString(s)
   if not s then return "" end
   return s:match("^%s*(.-)%s*$")
end

function GetSmartLoaderID()
    if not r.APIExists("CF_EnumerateActions") then return nil end
    local i = 0
    while true do
        local cmdId, name = r.CF_EnumerateActions(0, i)
        if not cmdId or cmdId == 0 then break end
        if name and name:lower():find(LOADER_SEARCH_NAME:lower(), 1, true) then
            local str_id = r.ReverseNamedCommandLookup(cmdId)
            if str_id then 
                if str_id:sub(1,1) ~= "_" then str_id = "_" .. str_id end
                return str_id 
            end
        end
        i = i + 1
    end
    return nil
end

-- =========================================================
-- UI FUNCTIONS
-- =========================================================

function DrawHelpPopup()
    local center = {r.ImGui_Viewport_GetCenter(r.ImGui_GetMainViewport(ctx))}
    r.ImGui_SetNextWindowPos(ctx, center[1], center[2], r.ImGui_Cond_Appearing(), 0.5, 0.5)
    
    if r.ImGui_BeginPopupModal(ctx, "Usage Instructions", true, r.ImGui_WindowFlags_AlwaysAutoResize()) then
        
        r.ImGui_TextColored(ctx, 0x44AA44FF, "HOW IT WORKS:")
        r.ImGui_BulletText(ctx, "This Manager creates a list of actions for THIS specific project.")
        r.ImGui_BulletText(ctx, "It uses a separate script called 'DocShadrach_Project Startup Loader'.")
        
        r.ImGui_Spacing(ctx)
        r.ImGui_Separator(ctx)
        r.ImGui_Spacing(ctx)
        
        r.ImGui_TextColored(ctx, 0xFFAA33FF, "SETUP STEPS:")
        
        r.ImGui_Text(ctx, "1. SAVE your project first.")
        r.ImGui_TextDisabled(ctx, "   (The script needs a folder to store the config file).")
        r.ImGui_Spacing(ctx)

        r.ImGui_Text(ctx, "2. Add actions to the list below.")
        r.ImGui_Spacing(ctx)

        r.ImGui_Text(ctx, "3. Click the GREEN button 'LINK LOADER (SWS)'.")
        r.ImGui_TextDisabled(ctx, "   (This automatically COPIES the Loader ID and OPENS the SWS dialog)")
        r.ImGui_Spacing(ctx)
        
        r.ImGui_Text(ctx, "4.") 
        r.ImGui_SameLine(ctx)
        r.ImGui_PushStyleColor(ctx, r.ImGui_Col_Text(), 0xFFFF00FF) -- Yellow
        r.ImGui_Text(ctx, "PASTE (Ctrl+V) the ID into the SWS dialog and press Enter.")
        r.ImGui_PopStyleColor(ctx)
        
        r.ImGui_Spacing(ctx)
        r.ImGui_Separator(ctx)
        r.ImGui_Spacing(ctx)
        
        if r.ImGui_Button(ctx, "Close", 120) then
            r.ImGui_CloseCurrentPopup(ctx)
        end
        r.ImGui_EndPopup(ctx)
    end
end

-- =========================================================
-- MAIN LOOP
-- =========================================================

function Loop()
    if not r.ImGui_ValidatePtr(ctx, 'ImGui_Context*') then
        ctx = r.ImGui_CreateContext('StartupManager')
    end
    
    r.ImGui_SetNextWindowBgAlpha(ctx, WINDOW_OPACITY)
    r.ImGui_SetNextWindowSize(ctx, WINDOW_W, WINDOW_H, r.ImGui_Cond_FirstUseEver())

    local visible, open = r.ImGui_Begin(ctx, 'Project Startup Manager', true)
    
    if visible then
        -- HEADER & SAVE WARNING
        local path = GetLocalFilePath()
        
        if not path then
            r.ImGui_TextColored(ctx, 0xFF0000FF, "IMPORTANT: SAVE PROJECT FIRST!")
            r.ImGui_TextDisabled(ctx, "(Actions stored in memory only)")
        else
            local display_path = path:match(".*[/\\](.*)") or path
            r.ImGui_TextDisabled(ctx, "File: " .. display_path)
        end
        
        r.ImGui_SameLine(ctx)
        local avail_w = r.ImGui_GetContentRegionAvail(ctx)
        r.ImGui_SetCursorPosX(ctx, r.ImGui_GetCursorPosX(ctx) + avail_w - 130)
        
        if r.ImGui_Button(ctx, "Help / Instructions") then
            r.ImGui_OpenPopup(ctx, "Usage Instructions")
        end
        
        DrawHelpPopup() 
        
        r.ImGui_Separator(ctx)
        
        -- WORKFLOW
        r.ImGui_Text(ctx, "Step 1: Find Action")
        if r.ImGui_Button(ctx, "Open Action List") then r.ShowActionList(0, 0) end
        r.ImGui_SameLine(ctx)
        r.ImGui_TextDisabled(ctx, "(Copy Command ID)")
        
        r.ImGui_Spacing(ctx)
        
        r.ImGui_Text(ctx, "Step 2: Add to List")
        if r.ImGui_Button(ctx, "Paste Action from Clipboard", -1, 30) then 
            local clip = ""
            if r.CF_GetClipboard then clip = r.CF_GetClipboard("") end
            if clip and clip ~= "" then
                clip = TrimString(clip) 
                local name = GetCommandName(clip)
                table.insert(actions_list, {id = clip, name = name, enabled = true})
                SaveData()
                SetStatus("Added: " .. name)
            else
                SetStatus("Clipboard is empty.", true)
            end
        end

        r.ImGui_Separator(ctx)
        
        -- LIST REGION
        if r.ImGui_BeginChild(ctx, "ListRegion", 0, -70) then -- Space for status
            if #actions_list == 0 then
                r.ImGui_TextDisabled(ctx, "No actions added yet.")
            else
                if r.ImGui_BeginTable(ctx, "ActionsTable", 4, r.ImGui_TableFlags_RowBg()) then
                    r.ImGui_TableSetupColumn(ctx, "#", r.ImGui_TableColumnFlags_WidthFixed(), 25)
                    r.ImGui_TableSetupColumn(ctx, "On", r.ImGui_TableColumnFlags_WidthFixed(), 30)
                    r.ImGui_TableSetupColumn(ctx, "Action Name", r.ImGui_TableColumnFlags_WidthStretch())
                    r.ImGui_TableSetupColumn(ctx, "Del", r.ImGui_TableColumnFlags_WidthFixed(), 30)
                    
                    local to_remove = nil
                    
                    for i, action in ipairs(actions_list) do
                        r.ImGui_TableNextRow(ctx)
                        r.ImGui_TableSetColumnIndex(ctx, 0)
                        r.ImGui_TextDisabled(ctx, tostring(i))
                        
                        -- CHECKBOX (BYPASS)
                        r.ImGui_TableSetColumnIndex(ctx, 1)
                        r.ImGui_PushID(ctx, i)
                        if r.ImGui_Checkbox(ctx, "", action.enabled) then
                            action.enabled = not action.enabled
                            SaveData()
                            -- FEEDBACK FOR BYPASS/ENABLE
                            if action.enabled then
                                SetStatus("Action Enabled (Saved)")
                            else
                                SetStatus("Action Bypassed (Saved)")
                            end
                        end
                        r.ImGui_PopID(ctx)
                        
                        r.ImGui_TableSetColumnIndex(ctx, 2)
                        if not action.enabled then r.ImGui_PushStyleColor(ctx, r.ImGui_Col_Text(), 0x888888FF) end
                        r.ImGui_Text(ctx, action.name)
                        if not action.enabled then r.ImGui_PopStyleColor(ctx) end
                        if r.ImGui_IsItemHovered(ctx) then r.ImGui_SetTooltip(ctx, "ID: " .. action.id) end
                        
                        -- DELETE
                        r.ImGui_TableSetColumnIndex(ctx, 3)
                        r.ImGui_PushStyleColor(ctx, r.ImGui_Col_Button(), 0xAA3333FF)
                        if r.ImGui_Button(ctx, "X##"..i) then to_remove = i end
                        r.ImGui_PopStyleColor(ctx)
                    end
                    r.ImGui_EndTable(ctx)
                    
                    if to_remove then
                        local name = actions_list[to_remove].name
                        table.remove(actions_list, to_remove)
                        SaveData()
                        SetStatus("Action Removed (Saved)")
                    end
                end
            end
            r.ImGui_EndChild(ctx)
        end
        
        r.ImGui_Separator(ctx)

        -- FOOTER BUTTONS
        if r.ImGui_Button(ctx, "RELOAD LIST") then 
            LoadActions() 
            SetStatus("List Reloaded")
        end
        r.ImGui_SameLine(ctx)
        
        local btn_color = 0x44AA44FF 
        r.ImGui_PushStyleColor(ctx, r.ImGui_Col_Button(), btn_color)
        if r.ImGui_Button(ctx, "LINK LOADER (SWS)") then
             local sws_action_id = r.NamedCommandLookup("_S&M_SET_PRJ_ACTION")
             if sws_action_id == 0 then
                 SetStatus("Error: SWS Extension not installed.", true)
             else
                 local smart_id = GetSmartLoaderID()
                 if smart_id then
                     if r.CF_SetClipboard then r.CF_SetClipboard(smart_id) end
                     r.Main_OnCommand(sws_action_id, 0)
                     SetStatus("Linked!!!") -- REQUESTED MESSAGE
                 else
                     SetStatus("Error: Loader not found in Action List.", true)
                 end
             end
        end
        r.ImGui_PopStyleColor(ctx)
        
        -- STATUS BAR (Timed)
        if status_msg ~= "" then
            if r.time_precise() > status_clear_time then
                status_msg = ""
            else
                r.ImGui_Spacing(ctx)
                -- Yellow color for visibility
                r.ImGui_TextColored(ctx, 0xFFFF00FF, ">> " .. status_msg)
            end
        end

        r.ImGui_End(ctx)
    end

    if open then r.defer(Loop) end
end

LoadActions()
Loop()
