-- @description Project Startup Loader
-- @author DocShadrach (Code by Your Reaper Lua Expert)
-- @version 1.0
-- @about Loads and executes project-specific startup actions. Must be linked via SWS Global/Project startup action.

local r = reaper

-- Constants
local EXT_SECTION = "StartupManager"
local EXT_KEY = "ActionList"
local FILE_NAME = "project_startup_actions.lua"

function GetProjectLocation()
    local _, proj_fn = r.EnumProjects(-1, "")
    if proj_fn and proj_fn ~= "" then
        local path = proj_fn:match("(.*[/\\])")
        return path
    end
    return nil
end

function RunAction(id_str)
    if not id_str or id_str == "" then return end
    local cmd = r.NamedCommandLookup(id_str)
    if cmd ~= 0 then
        r.Main_OnCommand(cmd, 0)
    end
end

-- A. Run from File (Secure Regex)
function RunFromFile(path)
    local f = io.open(path, "r")
    if not f then return false end
    
    local executed_any = false
    for line in f:lines() do
        if not line:match("^%s*%-%-") then
            local id = line:match('NamedCommandLookup%("([^"]+)"%)')
            if id then
                RunAction(id)
                executed_any = true
            end
        end
    end
    io.close(f)
    return executed_any
end

-- C. Generator (Restores file from Metadata)
function RegenerateFileFromData(path, data_string)
    local f = io.open(path, "w")
    if not f then return end
    
    f:write("-- Auto-generated by Project Startup Manager (Restored)\n")
    f:write("local r = reaper\n\n")
    
    for item in data_string:gmatch("([^;]+)") do
        local id, name, enabled = item:match("^([^|]+)|([^|]+)|([^|]+)")
        if not enabled then 
            id, name = item:match("^([^|]+)|(.*)")
            enabled = "1" 
        end
        
        if id then
            local prefix = ""
            if enabled == "0" then prefix = "-- " end
            if not name or name == "" then name = "Action" end
            f:write(string.format('%sr.Main_OnCommand(r.NamedCommandLookup("%s"), 0) -- %s\n', prefix, id, name))
        end
    end
    f:close()
end

-- B. Run from Metadata
function RunFromExtState_And_Regenerate(proj_path)
    local retval, data = r.GetProjExtState(0, EXT_SECTION, EXT_KEY)
    
    if retval == 1 and data ~= "" then
        for item in data:gmatch("([^;]+)") do
            local id, _, enabled = item:match("^([^|]+)|([^|]+)|([^|]+)")
            if not enabled then 
                id = item:match("^([^|]+)")
                enabled = "1" 
            end

            if id and enabled == "1" then
                RunAction(id)
            end
        end
        
        if proj_path then
            local target_file = proj_path .. FILE_NAME
            local f_check = io.open(target_file, "r")
            if not f_check then
                RegenerateFileFromData(target_file, data)
            else
                io.close(f_check)
            end
        end
        return true
    end
    return false
end

function Main()
    local executed_from_file = false
    local proj_path = GetProjectLocation()
    
    if proj_path then
        local target_file = proj_path .. FILE_NAME
        local f_check = io.open(target_file, "r")
        if f_check then
            io.close(f_check)
            executed_from_file = RunFromFile(target_file)
        end
    end

    if not executed_from_file then
        RunFromExtState_And_Regenerate(proj_path)
    end
end

Main()
